name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      # - env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     curl --request GET \
      #     --url "https://api.github.com/xianyubb/org_out" \
      #     --header "Authorization: Bearer $GH_TOKEN"
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: build
        run: |
          npm install
          tsc
          cp package.json dist/
          mkdir out
          7z a -tzip -r ../out/xianyubb-bot .
        # git config --local user.email "2149656630@qq.com"
        # git config --local user.name "xianyubb"
        # git add -f .
        # git commit -m "new"
      # - name: Push to anothor repository
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: xianyubb/org_out
      #     force: true
      # - name: upload
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Organization
      #     path: org_out/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: xianyubb-bot
          files: ./out/*
          